import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const app = express();
const PORT = 5000;

app.use(
  cors({
    origin: "http://localhost:5173",
  })
);

app.use(express.json());

const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey) {
  console.error("❌ GEMINI_API_KEY is missing from .env");
  process.exit(1);
}

const ai = new GoogleGenAI({
  apiKey,
});

// --------------------------------------------
// HEALTH CHECK
// --------------------------------------------

app.get("/api/health", (req, res) => {
  res.json({
    success: true,
    message: "TripRescue AI backend is running.",
  });
});

// --------------------------------------------
// GEMINI TEST
// --------------------------------------------

app.get("/api/test-gemini", async (req, res) => {
  try {
    const interaction = await ai.interactions.create({
      model: "gemini-3.6-flash",
      input:
        "Reply with exactly: TripRescue AI Gemini connection successful.",
    });

    res.json({
      success: true,
      message: interaction.output_text,
    });
  } catch (error) {
    console.error("Gemini error:", error);

    res.status(500).json({
      success: false,
      error: error.message || "Gemini request failed.",
    });
  }
});

// --------------------------------------------
// AI DISRUPTION ANALYSIS
// --------------------------------------------

app.post("/api/analyze-disruption", async (req, res) => {
  try {
    const {
      trip,
      disruption,
      impactAnalysis,
      recoveryPlans = [],
    } = req.body;

    if (!trip || !disruption || !impactAnalysis) {
      return res.status(400).json({
        success: false,
        error:
          "trip, disruption and impactAnalysis are required.",
      });
    }

    // Only send the information Gemini actually needs.
    const recoveryOptions = recoveryPlans.map((plan) => ({
      id: plan.id,
      name: plan.name,
      title: plan.title,
      description: plan.description,
      preferenceScore: plan.preferenceScore,
      scoreBreakdown: plan.scoreBreakdown,
      costImpact: plan.costImpact,
      timeImpact: plan.timeImpact,
      activitiesPreserved: plan.activitiesPreserved,
      itineraryPreservation: plan.itineraryPreservation,
      convenience: plan.convenience,
      reliability: plan.reliability,
      details: plan.details,
    }));

    const prompt = `
You are the decision-making intelligence inside TripRescue AI,
an intelligent travel disruption recovery system.

Your job is NOT to invent new travel plans.

You must evaluate the recovery plans already generated by the
TripRescue recovery engine and recommend the best existing plan.

The system uses a dependency-aware itinerary model.

When one event breaks, downstream events may also be affected.

--------------------------------------------------
TRIP
--------------------------------------------------

${JSON.stringify(trip, null, 2)}

--------------------------------------------------
DISRUPTION
--------------------------------------------------

${JSON.stringify(disruption, null, 2)}

--------------------------------------------------
IMPACT ANALYSIS
--------------------------------------------------

${JSON.stringify(impactAnalysis, null, 2)}

--------------------------------------------------
AVAILABLE RECOVERY PLANS
--------------------------------------------------

${JSON.stringify(recoveryOptions, null, 2)}

--------------------------------------------------
TASK
--------------------------------------------------

Analyze the disruption and compare the available recovery plans.

Consider:

1. Downstream impact on the itinerary
2. Traveler preferences
3. Additional cost
4. Additional travel time
5. Preservation of planned activities
6. Convenience
7. Reliability
8. Overall itinerary preservation

Choose exactly ONE plan from the supplied recovery plans.

IMPORTANT:
- Do not invent a new plan.
- Do not modify a plan.
- recommendedPlanId MUST exactly match one of the supplied plan IDs.
- Keep the reasoning concise and specific.
- Explain WHY the selected plan is better than the alternatives.

Return ONLY valid JSON.

Required JSON format:

{
  "recommendedPlanId": "exact-plan-id",
  "summary": "One concise sentence explaining the recommendation.",
  "reasoning": [
    "Reason 1",
    "Reason 2",
    "Reason 3"
  ],
  "primaryRisk": "The most important risk caused by the disruption.",
  "comparison": {
    "recommended": "Why the recommended plan wins.",
    "alternative1": "Why another option is weaker.",
    "alternative2": "Why another option is weaker."
  }
}
`;

    const interaction = await ai.interactions.create({
      model: "gemini-3.6-flash",
      input: prompt,
    });

    const rawOutput = interaction.output_text;

    console.log("\n========== GEMINI ANALYSIS ==========");
    console.log(rawOutput);
    console.log("=====================================\n");

    let aiResult;

    try {
      aiResult = JSON.parse(rawOutput);
    } catch (parseError) {
      // Gemini occasionally wraps JSON in markdown.
      const cleaned = rawOutput
        .replace(/```json/gi, "")
        .replace(/```/g, "")
        .trim();

      try {
        aiResult = JSON.parse(cleaned);
      } catch (secondParseError) {
        console.error("❌ Failed to parse Gemini JSON:", rawOutput);

        return res.status(500).json({
          success: false,
          error: "Gemini returned an invalid JSON response.",
          rawOutput,
        });
      }
    }

    // --------------------------------------------
    // VALIDATE RECOMMENDED PLAN
    // --------------------------------------------

    const validPlanIds = recoveryPlans.map((plan) => plan.id);

    if (!validPlanIds.includes(aiResult.recommendedPlanId)) {
      console.error(
        "❌ Gemini selected an invalid plan:",
        aiResult.recommendedPlanId
      );

      return res.status(500).json({
        success: false,
        error: "Gemini returned an invalid recovery plan ID.",
      });
    }

    // --------------------------------------------
    // RETURN AI DECISION
    // --------------------------------------------

    res.json({
      success: true,
      data: {
        recommendedPlanId: aiResult.recommendedPlanId,
        summary: aiResult.summary || "",
        reasoning: Array.isArray(aiResult.reasoning)
          ? aiResult.reasoning
          : [],
        primaryRisk: aiResult.primaryRisk || "",
        comparison: aiResult.comparison || {},
      },
    });
  } catch (error) {
    console.error("\n❌ AI DISRUPTION ANALYSIS ERROR");
    console.error(error);

    res.status(500).json({
      success: false,
      error:
        error.message ||
        "Failed to analyze disruption with Gemini.",
    });
  }
});

// --------------------------------------------
// START SERVER
// --------------------------------------------

app.listen(PORT, () => {
  console.log("");
  console.log("========================================");
  console.log("       TRIPRESCUE AI BACKEND");
  console.log("========================================");
  console.log(`Server: http://localhost:${PORT}`);
  console.log("Gemini API key: ✓ Loaded");
  console.log("Gemini model: gemini-3.6-flash");
  console.log("AI analysis endpoint: /api/analyze-disruption");
  console.log("========================================");
  console.log("");
});